import React from 'react';

/**
 * ReportDownload Component
 * Generate and download comparison report
 */
const ReportDownload = ({ comparison }) => {
  if (!comparison) {
    return null;
  }

  const generateTextReport = () => {
    const report = `
MONASTERY PRESERVATION - COMPARISON REPORT
==========================================

Location: ${comparison.location}
Structure Component: ${comparison.structureComponent}
Comparison Date: ${new Date(comparison.comparisonDate).toLocaleString()}

ANALYSIS RESULTS
----------------
SSIM Score: ${(comparison.ssimScore * 100).toFixed(2)}%
Severity Level: ${comparison.severityLevel}
Difference Percentage: ${comparison.analysis?.differencePercentage?.toFixed(2) || 'N/A'}%
Affected Area: ${comparison.analysis?.affectedArea?.toFixed(2) || 'N/A'}%
Regions Detected: ${comparison.analysis?.contourCount || 0}

RECOMMENDATIONS
---------------
${comparison.analysis?.recommendations || 'No recommendations available'}

IMAGE INFORMATION
-----------------
Baseline Image: ${comparison.baselineImage?.filename || 'N/A'}
Baseline Upload Date: ${comparison.baselineImage?.uploadDate ? new Date(comparison.baselineImage.uploadDate).toLocaleString() : 'N/A'}

Current Image: ${comparison.currentImage?.filename || 'N/A'}
Current Upload Date: ${comparison.currentImage?.uploadDate ? new Date(comparison.currentImage.uploadDate).toLocaleString() : 'N/A'}

PROCESSING DETAILS
------------------
Processing Time: ${comparison.processingTime}ms
Status: ${comparison.status}
Alert Flag: ${comparison.alertFlag ? 'YES - Requires Immediate Attention' : 'No'}

NOTES
-----
${comparison.notes || 'No additional notes'}

==========================================
Generated by Monastery Preservation System
==========================================
    `.trim();

    return report;
  };

  const handleDownloadText = () => {
    const report = generateTextReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `comparison_report_${comparison._id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const jsonData = JSON.stringify(comparison, null, 2);
    const blob = new Blob([jsonData], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `comparison_report_${comparison._id}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="report-download">
      <h4>Download Report</h4>
      <div className="download-buttons">
        <button onClick={handleDownloadText} className="btn-secondary">
          📄 Download Text Report
        </button>
        <button onClick={handleDownloadJSON} className="btn-secondary">
          📊 Download JSON Data
        </button>
      </div>
    </div>
  );
};

export default ReportDownload;
